Feat: add iterable_merge function
bpolaszek/php-iterable-functions pull request #45
Opened 2022-10-02 19:24 UTC by jdecool

Add `iterable_merge` function.

2022-10-10 12:04 UTC, bpolaszek requested changes
Hi @jdecool,

Thanks for your contribution & sorry for the late reply!

The following case does not succeed:

```php
$array1 = ['bar', 'baz'];
$array2 = ['bat', 'baz'];
$generator1 = fn () => yield from $array1;
$generator2 = fn () => yield from $array2;

expect(iterable_merge($generator1(), $generator2())->asArray())->toEqual(array_merge($array1, $array2));
```

2022-10-10 12:04 UTC, bpolaszek commented on src/iterable-functions.php
> +function iterable_merge(iterable $iterable, iterable ...$args): iterable
As of PHP 7.4, `array_merge()` can be used without arguments (it basically returns an empty array). I'd suggest doing the same here.

2022-10-10 21:26 UTC, jdecool commented
No problem @bpolaszek 

I've just pushed some updates.

2022-10-13 08:10 UTC, bpolaszek commented
Sounds good to me 🙂 

Can you please fix CI + advertise it in `README.md`?

Thanks! 🙏

2022-10-13 20:13 UTC, jdecool commented
> Can you please fix CI + advertise it in README.md?

Sure, everything should be OK now.

2022-10-14 07:30 UTC, jdecool commented
😮 it fails. 

Sorry i’ve missed one check

2022-10-14 12:05 UTC, jdecool commented
Everything is fine now is the CI  😌

2022-10-15 07:10 UTC, bpolaszek approved these changes

2022-10-15 07:11 UTC, merged

2022-10-15 07:11 UTC, bpolaszek commented
Thanks @jdecool, your contribution is very much appreciated! 👍

2022-10-15 08:41 UTC, simPod commented on src/iterable-functions.php
> + * @param iterable<TKey, TValue> ...$args
BTW I think this template will not work for merging iterables with different value types.

Also it seems, there's no support for typing it properly https://github.com/phpstan/phpstan/issues/3814#issuecomment-684779628

2022-10-15 12:32 UTC, JoshuaBehrens commented
Nice feature :)